=== Nk-Kyle/noam_impl/schemas/xsd/frequency.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
    xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="frequencyDoc" type="frequencyDocType" />
    <xs:complexType name="frequencyType">
        <xs:simpleContent>
            <xs:extension base="xs:float">
                <xs:attribute type="xs:string" name="type" use="optional" />
                <xs:attribute type="xs:string" name="name" use="optional" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="frequencyDocType">
        <xs:sequence>
            <xs:element type="frequencyType" name="frequency" maxOccurs="unbounded" minOccurs="0" />
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== Nk-Kyle/noam_impl/noam_impl/schemas/perpustakaan/frequency.xml
<?xml version="1.0" encoding="UTF-8"?>
<frequencyDoc xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../xsd/frequency.xsd">
    <frequency type="class" name="Member">10</frequency>
    <frequency type="class" name="Loan">10</frequency>
    <frequency type="class" name="Return">1</frequency>
    <frequency type="class" name="Book">1</frequency>
    <frequency type="class" name="Publisher">1</frequency>
    <frequency type="class" name="Author">1</frequency>
    <frequency type="relation" name="loaned">10</frequency>
    <frequency type="relation" name="records">10</frequency>
    <frequency type="relation" name="commits">10</frequency>
    <frequency type="relation" name="writes">1</frequency>
    <frequency type="relation" name="supplies">1</frequency>
    <frequency type="query" name="Q1">10</frequency>
    <frequency type="query" name="Q2">60</frequency>
    <frequency type="query" name="Q3">20</frequency>
    <frequency type="query" name="Q4">60</frequency>
    <frequency type="query" name="Q5">20</frequency>
</frequencyDoc>

=== Nk-Kyle/noam_impl/noam_impl/schemas/onlinestore/frequency.xml
<?xml version="1.0" encoding="UTF-8"?>
<frequencyDoc xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../xsd/frequency.xsd">
    <frequency type="class" name="Order">1</frequency>
    <frequency type="class" name="Carrier">1</frequency>
    <frequency type="class" name="Payment">1</frequency>
    <frequency type="class" name="Item">1</frequency>
    <frequency type="class" name="Customer">1</frequency>
    <frequency type="class" name="Product">1</frequency>
    <frequency type="class" name="Supplier">1</frequency>
    <frequency type="class" name="Category">1</frequency>
    <frequency type="query" name="Q1">15</frequency>
</frequencyDoc>
