=== Nk-Kyle/noam_impl/schemas/xsd/query.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
    xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="queryDoc" type="queryDocType" />
    <xs:complexType name="attributeType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="searchKey" use="optional" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="classType">
        <xs:sequence>
            <xs:element name="attribute" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute type="xs:string" name="searchKey" use="optional" />
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element type="relationType" name="relation" maxOccurs="unbounded" minOccurs="0" />
        </xs:sequence>
        <xs:attribute type="xs:string" name="name" use="optional" />
    </xs:complexType>
    <xs:complexType name="relationType">
        <xs:sequence>
            <xs:element type="classType" name="class" />
        </xs:sequence>
        <xs:attribute type="xs:string" name="name" use="optional" />
    </xs:complexType>
    <xs:complexType name="queryType">
        <xs:sequence>
            <xs:element type="classType" name="class" />
        </xs:sequence>
        <xs:attribute type="xs:string" name="name" use="optional" />
    </xs:complexType>
    <xs:complexType name="queryDocType">
        <xs:sequence>
            <xs:element type="queryType" name="query" maxOccurs="unbounded" minOccurs="0" />
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== Nk-Kyle/noam_impl/schemas/perpustakaan/query.xml
<?xml version="1.0" encoding="UTF-8"?>
<queryDoc xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../xsd/query.xsd">
    <query name="Q1"> <!-- Search book loan detail -->
        <class name="Book">
            <attribute searchKey="true">id</attribute>
            <relation name="records">
                <class name="Loan">
                    <attribute>id</attribute>
                    <attribute>loanedAt</attribute>
                    <relation name="loaned">
                        <class name="Member">
                            <attribute>id</attribute>
                            <attribute>type</attribute>
                            <attribute>name</attribute>
                            <attribute>studentId</attribute>
                            <attribute>year</attribute>
                            <attribute>employeeId</attribute>
                        </class>
                    </relation>
                    <relation name="commits">
                        <class name="Return">
                            <attribute>id</attribute>
                            <attribute>penalty</attribute>
                            <attribute>returnedAt</attribute>
                        </class>
                    </relation>
                </class>
            </relation>
        </class>
    </query>
    <query name="Q2"> <!-- Search book detail -->
        <class name="Book">
            <attribute searchKey="true">id</attribute>
            <attribute>name</attribute>
            <attribute>description</attribute>
            <attribute>language</attribute>
            <attribute>keywords</attribute>
            <relation name="writes">
                <class name="Author">
                    <attribute>id</attribute>
                    <attribute>name</attribute>
                </class>
            </relation>
            <relation name="supplies">
                <class name="Publisher">
                    <attribute>id</attribute>
                    <attribute>name</attribute>
                    <attribute>contact</attribute>
                </class>
            </relation>
            <relation name="catalogs">
                <class name="Category">
                    <attribute>name</attribute>
                    <attribute>subcategory</attribute>
                </class>
            </relation>
        </class>
    </query>
    <query name="Q3"> <!-- Search member loan detail -->
        <class name="Member">
            <attribute searchKey="true">id</attribute>
            <attribute>name</attribute>
            <relation name="loaned">
                <class name="Loan">
                    <attribute>id</attribute>
                    <attribute>loanedAt</attribute>
                    <relation name="records">
                        <class name="Book">
                            <attribute>id</attribute>
                            <attribute>name</attribute>
                            <attribute>description</attribute>
                        </class>
                    </relation>
                    <relation name="commits">
                        <class name="Return">
                            <attribute>id</attribute>
                            <attribute>penalty</attribute>
                            <attribute>returnedAt</attribute>
                        </class>
                    </relation>
                </class>
            </relation>
        </class>
    </query>
    <query name="Q4"> <!-- Search member Info -->
        <class name="Member">
            <attribute searchKey="true">id</attribute>
            <attribute>type</attribute>
            <attribute>name</attribute>
            <attribute>studentId</attribute>
            <attribute>year</attribute>
            <attribute>employeeId</attribute>
            <relation name="research">
                <class name="Faculty">
                    <attribute>id</attribute>
                    <attribute>name</attribute>
                </class>
            </relation>
            <relation name="place">
                <class name="Address">
                    <attribute>city</attribute>
                    <attribute>address</attribute>
                    <attribute>postal</attribute>
                </class>
            </relation>
        </class>
    </query>
    <query name="Q5"> <!-- Search author books -->
        <class name="Author">
            <attribute searchKey="true">id</attribute>
            <attribute>name</attribute>
            <relation name="writes">
                <class name="Book">
                    <attribute>id</attribute>
                    <attribute>name</attribute>
                    <relation name="supplies">
                        <class name="Publisher">
                            <attribute>id</attribute>
                            <attribute>name</attribute>
                            <attribute>contact</attribute>
                        </class>
                    </relation>
                    <relation name="catalogs">
                        <class name="Category">
                            <attribute>name</attribute>
                            <attribute>subcategory</attribute>
                        </class>
                    </relation>
                </class>
            </relation>
        </class>
    </query>
</queryDoc>

=== Nk-Kyle/noam_impl/noam_impl/schemas/testbase/query.xml
<?xml version="1.0" encoding="UTF-8"?>
<queryDoc xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../xsd/query.xsd">
    <query name="Q1">
        <class name="A">
            <attribute searchKey="true">id</attribute>
            <relation name="r_a_b">
                <class name="B">
                    <attribute>id</attribute>
                    <attribute>attrB1</attribute>
                    <attribute>attrB2</attribute>
                </class>
            </relation>
        </class>
    </query>
</queryDoc>

=== Nk-Kyle/noam_impl/noam_impl/schemas/onlinestore/query.xml
<?xml version="1.0" encoding="UTF-8"?>
<queryDoc xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../xsd/query.xsd">
    <query name="Q1">
        <class name="Order">
            <attribute searchKey="true">id</attribute>
            <relation name="consists_of">
                <class name="Item">
                    <relation name="references">
                        <class name="Product">
                        </class>
                    </relation>
                </class>
            </relation>
            <relation name="requests">
                <class name="Customer">
                </class>
            </relation>
        </class>
    </query>
</queryDoc>
