=== Nk-Kyle/noam_impl/schemas/xsd/query.full.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
    xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="query" type="queryType" />
    <xs:complexType name="classType" mixed="true">
        <xs:sequence>
            <xs:element type="xs:string" name="attribute" maxOccurs="unbounded" minOccurs="0" />
            <xs:element type="relationType" name="relation" maxOccurs="unbounded" minOccurs="0" />
        </xs:sequence>
        <xs:attribute type="xs:string" name="name" use="optional" />
    </xs:complexType>
    <xs:complexType name="qsType">
        <xs:sequence>
            <xs:element type="classType" name="class" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="relationType">
        <xs:sequence>
            <xs:element type="classType" name="class" />
        </xs:sequence>
        <xs:attribute type="xs:string" name="name" use="optional" />
    </xs:complexType>
    <xs:complexType name="qfType">
        <xs:sequence>
            <xs:element type="classType" name="class" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="qpType">
        <xs:sequence>
            <xs:element type="classType" name="class" maxOccurs="unbounded" minOccurs="0" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="queryType">
        <xs:sequence>
            <xs:element type="qsType" name="qs" />
            <xs:element type="qfType" name="qf" />
            <xs:element type="qpType" name="qp" />
        </xs:sequence>
        <xs:attribute type="xs:string" name="name" />
    </xs:complexType>
</xs:schema>

=== Nk-Kyle/noam_impl/schemas/perpustakaan/query.full.xml
<?xml version="1.0" encoding="UTF-8"?>
<query xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../xsd/query.full.xsd" name="Q1">
    <qs>
        <class name="Book">
            <attribute>id</attribute>
        </class>
    </qs>
    <qf>
        <class name="Book">
            <relation name="records">
                <class name="Loan">
                    <relation name="loaned">
                        <class name="Member" />
                    </relation>
                    <relation
                        name="commits">
                        <class name="Return" />
                    </relation>
                </class>
            </relation>
        </class>
    </qf>
    <qp>
        <class name="Member">
            <attribute>type</attribute>
            <attribute>name</attribute>
            <attribute>studentId</attribute>
            <attribute>year</attribute>
        </class>
        <class name="Loan">
            <attribute>loanedAt</attribute>
        </class>
        <class name="Return">
            <attribute>penalty</attribute>
            <attribute>returnedAt</attribute>
        </class>
    </qp>
</query>
